#!/usr/bin/env node
/**
 * Writes config.js from MAPBOX_ACCESS_TOKEN (or MAPBOX_TOKEN / MAPBOX_API_KEY).
 * Used by Netlify at build time, and locally via `node inject-env.js`.
 */
const fs = require('fs');
const path = require('path');

function loadDotEnv() {
    const envPath = path.join(__dirname, '.env');
    if (!fs.existsSync(envPath)) return;

    const text = fs.readFileSync(envPath, 'utf8');
    for (const line of text.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        const key = trimmed.slice(0, eq).trim();
        let value = trimmed.slice(eq + 1).trim();
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }
        if (process.env[key] == null) process.env[key] = value;
    }
}

loadDotEnv();

const token =
    process.env.MAPBOX_ACCESS_TOKEN ||
    process.env.MAPBOX_TOKEN ||
    process.env.MAPBOX_API_KEY ||
    '';

const contents = `// Generated by inject-env.js — do not edit by hand.
window.MAPBOX_ACCESS_TOKEN = ${JSON.stringify(token)};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), contents);

if (token) {
    console.log('Wrote config.js with Mapbox token.');
} else {
    console.warn(
        'Wrote config.js but MAPBOX_ACCESS_TOKEN is empty. Set it in Netlify env vars or a local .env file.'
    );
}
